import logging
import secrets
import threading
import time
from collections import deque

from django.conf import settings
from django.http import JsonResponse

CSP_NONCE_PLACEHOLDER = '__CSP_NONCE__'

_rate_limit_logger = logging.getLogger('budgetbook.security')


class CSPNonceMiddleware:
    """Per-request CSP nonce. Stored on request.csp_nonce so templates and
    response middleware can pick it up."""

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        request.csp_nonce = secrets.token_urlsafe(16)
        return self.get_response(request)


class ContentSecurityPolicyMiddleware:
    """Attach the configured Content-Security-Policy header.

    `__CSP_NONCE__` placeholders are substituted with the per-request nonce
    generated by CSPNonceMiddleware.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        if settings.CSP_ENABLED and 'Content-Security-Policy' not in response:
            policy = settings.CONTENT_SECURITY_POLICY
            nonce = getattr(request, 'csp_nonce', '')
            if nonce and CSP_NONCE_PLACEHOLDER in policy:
                policy = policy.replace(CSP_NONCE_PLACEHOLDER, nonce)
            response['Content-Security-Policy'] = policy
        return response


def csp_nonce(request):
    """Context processor exposing request.csp_nonce to templates."""
    return {'csp_nonce': getattr(request, 'csp_nonce', '')}


def static_version(request):
    """Context processor exposing STATIC_VERSION to templates as cache buster."""
    return {'STATIC_VERSION': getattr(settings, 'STATIC_VERSION', '')}


# ---------------------------------------------------------------------------
# Demo mode (public ポートフォリオ / self-host distribution 用)
# ---------------------------------------------------------------------------

_DEMO_SAFE_METHODS = {'GET', 'HEAD', 'OPTIONS', 'TRACE'}


class DemoModeWriteBlockMiddleware:
    """DEMO_MODE=1 かつ DEMO_ALLOW_WRITES=0 のとき、unsafe な HTTP メソッドを 403 でブロックする。

    GET / HEAD などの read-only リクエストは素通し。POST / PUT / PATCH / DELETE は
    `/accounts/login/` などログイン flow を除いて全て拒否する。

    通常運用（DEMO_MODE=0）では無効。
    """

    BLOCK_BYPASS_PATHS = (
        '/accounts/login/',
        '/accounts/logout/',
    )

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if not getattr(settings, 'DEMO_MODE', False):
            return self.get_response(request)
        if getattr(settings, 'DEMO_ALLOW_WRITES', False):
            return self.get_response(request)
        if request.method in _DEMO_SAFE_METHODS:
            return self.get_response(request)
        if request.path.startswith(self.BLOCK_BYPASS_PATHS):
            return self.get_response(request)
        return JsonResponse(
            {
                'status': 'demo_blocked',
                'message': 'これはデモ環境です。データの追加・編集・削除はできません。',
            },
            status=403,
        )


def demo_mode(request):
    """Context processor exposing demo mode flags to templates.

    base.html のバナー表示などで利用する。
    """
    return {
        'DEMO_MODE': getattr(settings, 'DEMO_MODE', False),
        'DEMO_ALLOW_WRITES': getattr(settings, 'DEMO_ALLOW_WRITES', False),
    }


_DEMO_USERNAME = 'demo'


class DemoAutoLoginMiddleware:
    """DEMO_MODE=1 かつ DEMO_AUTO_LOGIN=1 のとき、未認証リクエストを
    `demo` ユーザーとして自動ログインさせる。

    公開ポートフォリオ demo で「URL を開けば即閲覧開始できる」体験を実現する。
    DemoModeWriteBlockMiddleware と組み合わせる前提なので、自動ログインしても
    POST/PUT/DELETE は 403 でブロックされる（書き込み不可）。

    制約:
    - 既に他のユーザーで認証済みの場合は何もしない（ログインフォームから
      明示的に他ユーザーでログインしたケースを尊重）
    - `demo` ユーザーが DB に存在しない場合は何もしない（seed 済前提）
    - django-axes を経由しない programmatic login のため、ロックアウト判定の
      対象外（demo 用途として意図的）

    依存: AuthenticationMiddleware の後ろに置くこと。
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if (
            getattr(settings, 'DEMO_MODE', False)
            and getattr(settings, 'DEMO_AUTO_LOGIN', False)
            and not request.user.is_authenticated
        ):
            from django.contrib.auth import get_user_model, login
            User = get_user_model()
            try:
                demo_user = User.objects.get(username=_DEMO_USERNAME)
            except User.DoesNotExist:
                demo_user = None
            if demo_user is not None:
                # backend は AxesStandaloneBackend / ModelBackend のうち
                # ModelBackend を使う（axes をスキップ、programmatic login のため）
                demo_user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, demo_user)
        return self.get_response(request)


class _SlidingWindow:
    """単一プロセス内の per-key sliding window. axes と独立した二次防御。"""

    def __init__(self, max_events: int, window_seconds: float):
        self.max_events = max_events
        self.window_seconds = window_seconds
        self._buckets: dict[str, deque] = {}
        self._lock = threading.Lock()

    def hit(self, key: str) -> bool:
        now = time.monotonic()
        cutoff = now - self.window_seconds
        with self._lock:
            bucket = self._buckets.setdefault(key, deque())
            while bucket and bucket[0] < cutoff:
                bucket.popleft()
            if len(bucket) >= self.max_events:
                return False
            bucket.append(now)
            return True


def _client_ip_for_rate_limit(request) -> str:
    if getattr(settings, 'SECURE_PROXY_SSL_HEADER', None):
        forwarded = request.META.get('HTTP_X_FORWARDED_FOR', '')
        if forwarded:
            return forwarded.split(',')[0].strip()[:64]
    return (request.META.get('REMOTE_ADDR') or 'unknown')[:64]


class RateLimitMiddleware:
    """全ビュー対象の二次レート制限。

    既定: 1 IP あたり 600 req / 60 秒（=10 req/s 平均）。
    `RATE_LIMIT_ENABLED=0` で無効化。健全な家庭内利用ではまず引っかからない値。
    Cloudflare Access 前段の保護を補完する defense-in-depth。
    """

    def __init__(self, get_response):
        self.get_response = get_response
        self.enabled = getattr(settings, 'RATE_LIMIT_ENABLED', True)
        max_events = int(getattr(settings, 'RATE_LIMIT_MAX_EVENTS', 600))
        window = float(getattr(settings, 'RATE_LIMIT_WINDOW_SECONDS', 60))
        self._window = _SlidingWindow(max_events=max_events, window_seconds=window)
        # /healthz / static は対象外
        self._exempt_prefixes = ('/healthz', '/static/')

    def __call__(self, request):
        if not self.enabled or request.path.startswith(self._exempt_prefixes):
            return self.get_response(request)
        ip = _client_ip_for_rate_limit(request)
        if not self._window.hit(ip):
            _rate_limit_logger.warning(
                'rate_limit_blocked',
                extra={'event': 'rate_limit', 'ip': ip, 'path': request.path},
            )
            return JsonResponse(
                {'status': 'error', 'detail': 'rate limit exceeded'},
                status=429,
            )
        return self.get_response(request)
