# Generated by Django 5.2.13 on 2026-04-17 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="opening_balance",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="初期残高",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="金額",
            ),
        ),
    ]
