# Generated by Django 5.2.13 on 2026-05-02 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_integer_amounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="金額",
                    ),
                ),
                ("description", models.CharField(max_length=120, verbose_name="摘要")),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="ledger.account",
                        verbose_name="出金元口座",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="ledger.account",
                        verbose_name="入金先口座",
                    ),
                ),
            ],
            options={
                "verbose_name": "振替",
                "verbose_name_plural": "振替",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
