# Generated by Django 5.2.13 on 2026-05-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="グループ名"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
            ],
            options={
                "verbose_name": "支出カテゴリグループ",
                "verbose_name_plural": "支出カテゴリグループ",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseGroupCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_group_membership",
                        to="ledger.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="ledger.expensegroup",
                        verbose_name="グループ",
                    ),
                ),
            ],
            options={
                "verbose_name": "グループ所属カテゴリ",
                "verbose_name_plural": "グループ所属カテゴリ",
                "ordering": ["group__sort_order", "category__name"],
            },
        ),
    ]
