# Generated by Django 5.2.13 on 2026-05-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_expensegroup_expensegroupcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyClosing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(unique=True, verbose_name="対象月")),
                (
                    "closed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="締め日時"),
                ),
                ("opening_carry", models.IntegerField(verbose_name="月初繰越")),
                ("income", models.IntegerField(verbose_name="収入")),
                ("expense", models.IntegerField(verbose_name="支出")),
                ("net", models.IntegerField(verbose_name="当月収支")),
                ("closing_balance", models.IntegerField(verbose_name="月末残高")),
                (
                    "account_balances",
                    models.JSONField(blank=True, verbose_name="口座別残高スナップショット"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="締め処理者",
                    ),
                ),
            ],
            options={
                "verbose_name": "月次締め",
                "verbose_name_plural": "月次締め",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="AccountReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("reconciled_on", models.DateField(verbose_name="照合日")),
                ("book_balance", models.IntegerField(verbose_name="帳簿残高")),
                ("actual_balance", models.IntegerField(verbose_name="実残高")),
                ("difference", models.IntegerField(verbose_name="差額")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ledger.account",
                        verbose_name="口座",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
            ],
            options={
                "verbose_name": "口座残高照合",
                "verbose_name_plural": "口座残高照合",
                "ordering": ["-reconciled_on", "account__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "reconciled_on"),
                        name="unique_reconciliation_account_date",
                    )
                ],
            },
        ),
    ]
