# Generated by Django 5.2.13 on 2026-05-03 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_monthlyclosing_accountreconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記録日時"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "作成"),
                            ("update", "更新"),
                            ("delete", "削除"),
                            ("deactivate", "無効化"),
                            ("close", "締め"),
                            ("reconcile", "照合"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(max_length=80, verbose_name="対象モデル"),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=80, verbose_name="対象ID"),
                ),
                (
                    "target_repr",
                    models.CharField(max_length=200, verbose_name="対象表示名"),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=200, verbose_name="概要"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="補足情報"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="ledger_audi_created_773852_idx"
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="ledger_audi_target__6a6a09_idx",
                    ),
                    models.Index(
                        fields=["action"], name="ledger_audi_action_8f67dc_idx"
                    ),
                ],
            },
        ),
    ]
