# Generated by Django 5.2.13 on 2026-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="section",
            field=models.CharField(
                choices=[
                    ("food_daily", "食品・日用品"),
                    ("dining_out", "外食"),
                    ("housing", "住居費"),
                    ("housing_misc", "住居関連"),
                    ("utility", "光熱・通信"),
                    ("transport", "交通"),
                    ("medical", "医療・健康"),
                    ("edu_leisure", "教養・娯楽"),
                    ("apparel_beauty", "衣料・美容"),
                    ("social", "交際・贈答"),
                    ("insurance_tax", "保険・税"),
                    ("saving_invest", "貯蓄・投資"),
                    ("other", "その他"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="大分類",
            ),
        ),
    ]
