# Generated by Django 5.2.13 on 2026-05-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0009_ensure_food_daily_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[("asset", "資産"), ("liability", "負債")],
                db_index=True,
                default="asset",
                max_length=10,
                verbose_name="会計区分",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="tax_tag",
            field=models.CharField(
                choices=[
                    ("none", "対象外"),
                    ("medical", "医療費控除"),
                    ("donation", "寄附金（ふるさと納税等）"),
                    ("business", "事業経費"),
                    ("other", "その他控除"),
                ],
                db_index=True,
                default="none",
                max_length=20,
                verbose_name="税控除タグ",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="opening_balance",
            field=models.IntegerField(default=0, verbose_name="初期残高"),
        ),
    ]
