# Generated by Django 5.2.13 on 2026-05-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_account_kind_category_tax_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "annual_rate_bp",
                    models.IntegerField(
                        default=0,
                        help_text="basis point で入力。15.00% なら 1500、0.5% なら 50。",
                        verbose_name="年利 (bp)",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("revolving", "リボ払い"),
                            ("eq_pi", "元利均等"),
                            ("eq_p", "元金均等"),
                            ("fixed", "定額分割"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="返済方式",
                    ),
                ),
                (
                    "monthly_payment",
                    models.IntegerField(
                        default=0,
                        help_text="実額が変動する場合は目安値で OK。0 なら未設定として扱う。",
                        verbose_name="月次返済額（目安）",
                    ),
                ),
                (
                    "payment_day",
                    models.IntegerField(
                        default=0,
                        help_text="1〜31 の範囲。0 は未設定。",
                        verbose_name="引落日",
                    ),
                ),
                (
                    "payoff_date",
                    models.DateField(blank=True, null=True, verbose_name="完済予定日"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="契約日・引落口座・契約番号など。",
                        verbose_name="備考",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_profile",
                        to="ledger.account",
                        verbose_name="負債口座",
                    ),
                ),
            ],
            options={
                "verbose_name": "負債プロファイル",
                "verbose_name_plural": "負債プロファイル",
            },
        ),
    ]
