# Generated by Django 5.2.13 on 2026-05-06 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0011_loanprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("month", models.DateField(db_index=True, verbose_name="対象月")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("food_daily", "食品・日用品"),
                            ("dining_out", "外食"),
                            ("housing", "住居費"),
                            ("housing_misc", "住居関連"),
                            ("utility", "光熱・通信"),
                            ("transport", "交通"),
                            ("medical", "医療・健康"),
                            ("edu_leisure", "教養・娯楽"),
                            ("apparel_beauty", "衣料・美容"),
                            ("social", "交際・贈答"),
                            ("insurance_tax", "保険・税"),
                            ("saving_invest", "貯蓄・投資"),
                            ("other", "その他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="大分類",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="予算額",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
            ],
            options={
                "verbose_name": "月次予算（大分類）",
                "verbose_name_plural": "月次予算（大分類）",
                "ordering": ["-month", "section"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "section"), name="unique_section_budget_month"
                    )
                ],
            },
        ),
    ]
