# Generated by Django 5.2.13 on 2026-05-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0012_sectionbudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanprofile",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                help_text="毎月の返済を自動生成する場合に指定。資産口座のみ。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_payments_from",
                to="ledger.account",
                verbose_name="引落元口座",
            ),
        ),
    ]
