# Generated by Django 5.2.13 on 2026-05-14 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0013_loanprofile_source_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualIncomeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, unique=True, verbose_name="対象年"
                    ),
                ),
                (
                    "gross_income",
                    models.IntegerField(
                        help_text="給与所得控除後の金額（源泉徴収票の該当欄）",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="総所得金額",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
            ],
            options={
                "verbose_name": "年次所得スナップショット",
                "verbose_name_plural": "年次所得スナップショット",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="MedicalExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("paid_date", models.DateField(db_index=True, verbose_name="支払日")),
                ("patient", models.CharField(max_length=50, verbose_name="受診者")),
                (
                    "provider",
                    models.CharField(max_length=120, verbose_name="医療機関・薬局名"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("treatment", "診療・治療（病院・歯科）"),
                            ("medicine", "医薬品（処方薬・市販薬）"),
                            ("care_insurance", "介護保険サービス"),
                            ("other", "その他（通院交通費 等）"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="区分",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="支払額",
                    ),
                ),
                (
                    "reimbursement",
                    models.IntegerField(
                        default=0,
                        help_text="保険金・出産育児一時金・高額療養費等で補填された金額",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="補填額",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_expense_set",
                        to="ledger.transaction",
                        verbose_name="紐付け取引",
                    ),
                ),
            ],
            options={
                "verbose_name": "医療費",
                "verbose_name_plural": "医療費",
                "ordering": ["-paid_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("transaction__isnull", False)),
                        fields=("transaction",),
                        name="uniq_medical_expense_per_transaction",
                    )
                ],
            },
        ),
    ]
