# Generated by Django 5.2.13 on 2026-05-14 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0014_medical_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurancePremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(db_index=True, verbose_name="対象年"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("life_general", "一般生命保険料"),
                            ("life_care_medical", "介護医療保険料"),
                            ("life_annuity", "個人年金保険料"),
                            ("earthquake", "地震保険料"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="区分",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("new", "新契約（2012/1/1 以降）"),
                            ("old", "旧契約（2011/12/31 以前）"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="契約区分",
                    ),
                ),
                (
                    "insurer",
                    models.CharField(max_length=120, verbose_name="保険会社名"),
                ),
                (
                    "policy_number",
                    models.CharField(
                        blank=True,
                        help_text="控除証明書の証券番号（任意、本人識別用）",
                        max_length=60,
                        verbose_name="証券番号",
                    ),
                ),
                (
                    "annual_amount",
                    models.IntegerField(
                        help_text="控除証明書の「申告額」または「年間払込予定額」",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="年間支払保険料",
                    ),
                ),
                (
                    "submitted_in_year_end_adjustment",
                    models.BooleanField(
                        default=False,
                        help_text="ON にすると確定申告レポートでは除外される",
                        verbose_name="年末調整で提出済",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
            ],
            options={
                "verbose_name": "保険料控除",
                "verbose_name_plural": "保険料控除",
                "ordering": ["-year", "category", "-id"],
                "indexes": [
                    models.Index(
                        fields=["year", "category"], name="ledger_insu_year_edda7f_idx"
                    )
                ],
            },
        ),
    ]
