# Generated by Django 5.2.13 on 2026-05-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0015_insurance_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="支払先名"
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False,
                        max_length=120,
                        unique=True,
                        verbose_name="正規化支払先名",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
            ],
            options={
                "verbose_name": "支払先",
                "verbose_name_plural": "支払先",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="ledger.payee",
                verbose_name="支払先",
            ),
        ),
        migrations.CreateModel(
            name="PayeeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("alias", models.CharField(max_length=120, verbose_name="別名")),
                (
                    "normalized_alias",
                    models.CharField(
                        editable=False,
                        max_length=120,
                        unique=True,
                        verbose_name="正規化別名",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="ledger.payee",
                        verbose_name="支払先",
                    ),
                ),
            ],
            options={
                "verbose_name": "支払先別名",
                "verbose_name_plural": "支払先別名",
                "ordering": ["alias"],
            },
        ),
    ]
