# Generated by Django 5.2.13 on 2026-05-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0016_payee_master"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="支払手段名"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "現金"),
                            ("bank", "銀行口座"),
                            ("credit_card", "クレジットカード"),
                            ("debit_card", "デビットカード"),
                            ("electronic_money", "電子マネー"),
                            ("qr", "QR決済"),
                            ("other", "その他"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="種別",
                    ),
                ),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(default=0, verbose_name="締日"),
                ),
                (
                    "settlement_day",
                    models.PositiveSmallIntegerField(default=0, verbose_name="引落日"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="この支払手段で通常残高が動く口座。クレジットカードなら負債口座。",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_methods",
                        to="ledger.account",
                        verbose_name="通常利用口座",
                    ),
                ),
                (
                    "settlement_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="クレジットカード等の引落元となる資産口座。",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_payment_methods",
                        to="ledger.account",
                        verbose_name="引落元口座",
                    ),
                ),
            ],
            options={
                "verbose_name": "支払手段",
                "verbose_name_plural": "支払手段",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="ledger.paymentmethod",
                verbose_name="支払手段",
            ),
        ),
    ]
