# Generated by Django 5.2.13 on 2026-05-24 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0017_payment_method_master"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("update", "カテゴリ編集"),
                            ("reclassify", "取引再分類"),
                            ("deactivate", "無効化"),
                            ("reactivate", "有効化"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "before",
                    models.JSONField(blank=True, default=dict, verbose_name="変更前"),
                ),
                (
                    "after",
                    models.JSONField(blank=True, default=dict, verbose_name="変更後"),
                ),
                (
                    "affected_transaction_count",
                    models.PositiveIntegerField(default=0, verbose_name="対象取引数"),
                ),
                (
                    "includes_closed_month",
                    models.BooleanField(default=False, verbose_name="締め済み月を含む"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="理由")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_logs",
                        to="ledger.category",
                        verbose_name="対象カテゴリ",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "カテゴリ変更履歴",
                "verbose_name_plural": "カテゴリ変更履歴",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="ledger_cate_action_145cf7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ledger_cate_created_828e3b_idx"
                    ),
                ],
            },
        ),
    ]
