# Generated by audit hardening on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_category_change_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'id'], name='ledger_tx_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='ledger_tx_acct_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='ledger_tx_cat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payee', 'date'], name='ledger_tx_payee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method', 'date'], name='ledger_tx_pm_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['date', 'id'], name='ledger_transfer_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_account', 'date'], name='ledger_transfer_from_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_account', 'date'], name='ledger_transfer_to_date_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreconciliation',
            index=models.Index(fields=['-reconciled_on', 'account'], name='ledger_recon_date_acct_idx'),
        ),
    ]
