#!/usr/bin/env bash
# install_git_hooks.sh — pre-commit hook をインストール (private repo 同型)
#
# 公開 demo repo のため private 由来機微情報の混入を物理ブロックする。
# Main PC + Laptop 両方で 1 度実行する必要あり (.git/hooks/ は Git 管理外)。

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

if [[ ! -d "$HOOK_DIR" ]]; then
  echo "[hooks] .git/hooks/ が見つかりません。" >&2
  exit 1
fi

if [[ -f "$HOOK_FILE" ]]; then
  cp "$HOOK_FILE" "$HOOK_FILE.bak.$(date +%s)"
  echo "[hooks] 既存 pre-commit を backup"
fi

cat > "$HOOK_FILE" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
else
  PYTHON_BIN="python"
fi
export PYTHON_BIN
if [[ -f "$REPO_ROOT/scripts/audit_docs_sensitive.sh" ]]; then
  bash "$REPO_ROOT/scripts/audit_docs_sensitive.sh" --staged
fi
if [[ -f "$REPO_ROOT/packaging/check_release_ready.py" ]]; then
  "$PYTHON_BIN" "$REPO_ROOT/packaging/check_release_ready.py"
fi
EOF

chmod +x "$HOOK_FILE"
echo "[hooks] pre-commit hook をインストールしました: $HOOK_FILE"
echo "[hooks] bypass したい場合: git commit --no-verify (public repo では原則使わない)"